name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Download env file from S3
        run: |
          aws s3 cp s3://czakuan-env/.env.production .env.production

      - name: Build project
        run: yarn build

      - name: Archive build files
        run: zip -r build.zip .next public package.json yarn.lock prisma/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-52-79-47-97.ap-northeast-2.compute.amazonaws.com << 'EOF'
            sudo mkdir -p /home/ec2-user/czakuan
            sudo chown ec2-user:ec2-user /home/ec2-user/czakuan
          EOF
          scp -o StrictHostKeyChecking=no build/build.zip ec2-user@ec2-52-79-47-97.ap-northeast-2.compute.amazonaws.com:/home/ec2-user/czakuan
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-52-79-47-97.ap-northeast-2.compute.amazonaws.com << 'EOF'
            cd /home/ec2-user/czakuan
            unzip -o build.zip
            chmod 600 .env.production
            aws s3 cp s3://czakuan-env/.env.production .env

            if [ ! -d "node_modules" ]; then yarn install --production; fi
            yarn prisma generate --schema=./prisma/schema.prisma

            pm2 delete czakuan || true
            pm2 start 'yarn start' --name czakuan
            pm2 startup
            pm2 save
          EOF
